### ISSUE TITLE
Support "shell" language

### ISSUE THREAD

**Issue by dufferzafar** [markedjs/marked#1289]
**Describe the feature**

Some people use "shell" instead of "bash" when writing fenced code blocks. Github supports that, and so should marked.

I think it will be straightforward too, as we just have to add an alias for bash.

I faced this issue when running [`gwtc`](https://github.com/yakivmospan/github-wikito-converter) on the bitcoin core codebase, [which does this](https://github.com/bitcoin/bitcoin/blame/master/doc/build-unix.md#L179).

Currently, my workaround is to manually edit the files and change \```shell to \```bash

**Comment by Martii** [comment]
Client side or Server side?

Server side we use *highlight.js*  and it seems to [already have this alias](https://github.com/isagalaev/highlight.js/blob/master/docs/css-classes-reference.rst#language-names-and-aliases). Haven't tried this DOM side yet. e.g. what highlighting are you using?

**Comment by dufferzafar** [comment]
I did this server side. I ran into this by running [github-wikito-converter](https://github.com/yakivmospan/github-wikito-converter) on locally cloned Bitcoin's Readme files.

```
$ gwtc -f pdf .

Unhandled rejection Error: Unknown language: "shell"
Please report this to https://github.com/markedjs/marked.
    at Object.highlight (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/highlight.js/lib/highlight.js:443:13)
    at Renderer.mainRenderer.code (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/markdown.js:34:79)
    at Parser.tok (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:1058:28)
    at Parser.parse (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:1003:17)
    at Function.Parser.parse (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:985:17)
    at marked (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/marked/lib/marked.js:1322:19)
    at Markdown.convertMarkdownString (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/markdown.js:109:14)
    at Markdown.convertMarkdownFile (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/markdown.js:116:19)
    at WikiConverter.<anonymous> (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:87:41)
    at Array.forEach (native)
    at WikiConverter.computePages (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:83:27)
    at WikiConverter.getPages (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:96:14)
    at PdfWriter.write (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/pdf-writer.js:43:34)
    at WikiConverter.<anonymous> (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/dist/wiki-converter.js:65:42)
    at tryCatcher (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/dufferzafar/.nvm/versions/node/v7.9.0/lib/node_modules/github-wikito-converter/node_modules/bluebird/js/main/promise.js:510:31)
```

**Comment by Martii** [comment]
@dufferzafar 
It would appear they are using an older major semver'sion at [/yakivmospan/github-wikito-converter/blob/`13dbc7e`/package.json#L64](https://github.com/yakivmospan/github-wikito-converter/blob/13dbc7ee7b1589dee15b7320ffff8d8f49a52a93/package.json#L64).  See [*highlight.js*@9.12.0](https://www.npmjs.com/package/highlight.js). Long story short their dependency at that project is behind by quite a bit.

**Comment by dufferzafar** [comment]
I've created an issue there. Since there's nothing to fix in `marked` - this can be closed?

**Comment by dufferzafar** [comment]
Thanks for mentioning the node EOL bit, I don't dabble with JS much so would never have known that it was EOLed. I'll update to v10.

**Comment by joshbruce** [comment]
Going to close per @dufferzafar's mention and feeling it is resolved.

I though issue creators could close their own issues?? But the surrounding conversation is making me second guess myself.

**Comment by Martii** [comment]
@joshbruce 
The labels threw me off as if @UziTech had an idea that wasn't covered... but yes most of the time openers can usually close if they want to.
