### ISSUE TITLE
TypeError: Cannot read property 'rest' of undefined

### ISSUE THREAD

**Issue by sw-yx** [markedjs/marked#1547]
**Describe the bug**

it said to report this while running my code so i'm reporting

```bash

/Users/swyx/Work/swyxdotio/node_modules/marked/lib/marked.js:1640
    throw e;
    ^

TypeError: Cannot read property 'rest' of undefined
Please report this to https://github.com/markedjs/marked.
    at Object.tokenize (/Users/swyx/Work/swyxdotio/node_modules/prismjs/prism.js:414:22)
    at Object.highlight (/Users/swyx/Work/swyxdotio/node_modules/prismjs/prism.js:280:18)
    at Renderer.renderer.code (/Users/swyx/Work/swyxdotio/sapper_markdown_code.js:43:37)
    at Parser.tok (/Users/swyx/Work/swyxdotio/node_modules/marked/lib/marked.js:1206:28)
    at Parser.parse (/Users/swyx/Work/swyxdotio/node_modules/marked/lib/marked.js:1149:17)
    at Function.Parser.parse (/Users/swyx/Work/swyxdotio/node_modules/marked/lib/marked.js:1131:17)
    at marked (/Users/swyx/Work/swyxdotio/node_modules/marked/lib/marked.js:1632:19)
    at fs.readdirSync.map (/Users/swyx/Work/swyxdotio/sapper_markdown_code.js:59:20)
    at Array.map (<anonymous>)
    at getPosts (/Users/swyx/Work/swyxdotio/sapper_markdown_code.js:15:6)
```

**To Reproduce**
sorry i dont have a repro yet, still investigating

**Comment by sw-yx** [comment]
it was caused by passing an unrecognized language into PrismJS.languages:

```js
const highlighted = PrismJS.highlight(source, PrismJS.languages[plang], lang)
```

**Comment by UziTech** [comment]
Sounds like you figured out the issue. If that is not the case feel free to reopen this.

**Comment by sw-yx** [comment]
yeah :) but you may want to have nicer error handling around renderers.

**Comment by UziTech** [comment]
I agree, if you want to make a PR I would be happy to review it?

**Comment by sw-yx** [comment]
ohh man i brought this on my self didnt i
