### ISSUE TITLE
TypeError: str.substr is not a function

### ISSUE THREAD

**Issue by twodayslate** [markedjs/marked#1623]
**Describe the bug**

```
/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/marked.js:111
    throw e;
    ^

TypeError: str.substr is not a function
Please report this to https://github.com/markedjs/marked.
    at rtrim (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/helpers.js:200:14)
    at resolveUrl (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/helpers.js:104:30)
    at cleanUrl (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/helpers.js:81:12)
    at Renderer.link (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/Renderer.js:135:12)
    at InlineLexer.outputLink (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/InlineLexer.js:247:23)
    at InlineLexer.output (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/InlineLexer.js:119:21)
    at Parser.parseText (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/Parser.js:78:24)
    at Parser.tok (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/Parser.js:181:20)
    at Parser.tok (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/Parser.js:152:24)
    at Parser.parse (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/Parser.js:47:19)
    at Function.parse (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/Parser.js:30:19)
    at marked (/Users/twodayslate/Development/swiftpackageregistry/node_modules/marked/src/marked.js:103:19)
    at /Users/twodayslate/Development/swiftpackageregistry/app.js:308:46
    at /Users/twodayslate/Development/swiftpackageregistry/app.js:225:25
    at /Users/twodayslate/Development/swiftpackageregistry/node_modules/dockerode/lib/exec.js:128:7
    at Modem.buildPayload (/Users/twodayslate/Development/swiftpackageregistry/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:311:7)
    at IncomingMessage.<anonymous> (/Users/twodayslate/Development/swiftpackageregistry/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:269:14)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**To Reproduce**

I am getting the README file from https://github.com/apple/swift-argument-parser using octonode and dockernode
```
                                var url = new URL(repo_info.html_url)
                                url.hostname = "raw.githubusercontent.com"
                                url.pathname = url.pathname + "/" + release_tag
                                var marked = require('marked');
                                marked.setOptions({
                                    baseUrl: url,
                                    renderer: new marked.Renderer(),
                                    highlight: function(code, language) {
                                        const hljs = require('highlight.js');
                                        const validLanguage = hljs.getLanguage(language) ? language : 'plaintext';
                                        return hljs.highlight(validLanguage, code).value;
                                      },
                                      gfm: true,
                                      breaks: true,
                                });

                                var readme = marked(stdout);
```

**Expected behavior**

No error thrown

**Comment by styfle** [comment]
Try `baseUrl: url.toString()` or ``baseUrl: url.href` so that the base is a string instead of URL object.

**Comment by twodayslate** [comment]
That fixed it. Strange it didn't throw an error on other repositories. 

Thank you!
