### ISSUE TITLE
<img/> causing marked to fail

### ISSUE THREAD

**Issue by mcclowes** [markedjs/marked#1801]
**Marked version:** `marked@1.2.2`

**Describe the bug**
I recently bumped by version of marked.

My markdown file includes a line of html: 
`<img src='https://marked.js.org/img/logo-black.svg' />`

If I remove it, it all works fine. With that line included, I get the following output:
```
(node:79672) UnhandledPromiseRejectionWarning: ReferenceError: _ is not defined
Please report this to https://github.com/markedjs/marked.
    at Renderer.renderer.html (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/handbooker/lib/scripts/generate/html/readMarkdownFile.js:17:3)
    at Parser.parse (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/marked/src/Parser.js:166:32)
    at Function.parse (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/marked/src/Parser.js:27:19)
    at marked (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/marked/src/marked.js:110:19)
    at readMarkdownFile (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/handbooker/lib/scripts/generate/html/readMarkdownFile.js:29:33)
    at handleTargetPages (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/handbooker/lib/scripts/generate/html/html.js:48:76)
    at generateHtml (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/handbooker/lib/scripts/generate/html/html.js:62:14)
    at _callee$ (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/handbooker/lib/scripts/generate/pdf/pdf.js:74:41)
    at tryCatch (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/maxclaytoncowes/Development/metamagic-games/dnd-homebrews/node_modules/regenerator-runtime/runtime.js:293:22)
(node:79672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

1. Clone this repo: https://github.com/metamagic-games/dnd-homebrews
2. `cd dnd-homebrews && npm install && npm run build`
3. See the above error message

**Expected behavior**
The html tag to be handled correctly.

**Comment by UziTech** [comment]
looks like the issue is in https://github.com/metamagic-games/handbooker/blob/master/src/scripts/generate/html/readMarkdownFile.js

You are using lodash (`_`) but not importing it.

**Comment by mcclowes** [comment]
Apologies!
