### ISSUE TITLE
Error: 105,110,118,97,108,105,100,...

### ISSUE THREAD

**Issue by GauBen** [markedjs/marked#2295]
**Marked version:** 3.0.8

**Describe the bug**
Typedoc fails and blames Marked

**To Reproduce**
1. `git clone https://github.com/GauBen/svelte-tenor && cd svelte-tenor`
2. `yarn install`
3. `yarn add typedoc`
4. `yarn typedoc src/lib`

Output:
```console
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 4.0, 4.1, 4.2, 4.3, 4.4
TypeDoc exiting with unexpected error:
Error: 105,110,118,97,108,105,100,32,112,97,116,116,101,114,110,32,105,110,32,108,111,111,107,45,98,101,104,105,110,100
Please report this to https://github.com/markedjs/marked.
    at OnigScanner.findNextMatchSync (/home/Gautier/projects/svelte-tenor/node_modules/onigasm/lib/OnigScanner.js:100:27)
    at /home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:9891
    at R (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:10242)
    at f (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:12144)
    at S (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:11997)
    at w (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:9336)
    at f (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:13085)
    at S (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:11997)
    at e._tokenize (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:8354)
    at e.tokenizeLine2 (/home/Gautier/projects/svelte-tenor/node_modules/vscode-textmate/release/main.js:1:7575)
```

It looks like the error does not even come from Marked, but I'm asking for help here first.

I tried downgrading to typescript 4.4 and it only removes the warning.

**Expected behavior**
Typedoc should produce a basic documentation

Node version: 16.13.0
Yarn version: 3.1.0 (with node_modules)

**Comment by UziTech** [comment]
Looks like this is an error in a tokenizer provided typedoc or one of it's dependencies.
