### ISSUE TITLE
Blog Post not readable

### ISSUE THREAD

**Issue by Patrick-Pr** [markedjs/marked#3018]
**Marked version:**

**Describe the bug**
If I visit the following blog post https://www.stepanrutz.com/blog/postgresql-trigram. The content will show for a brief second and then disappear. If I then open the Dev Tools and look at the console the following Error is logged.
```
index-df0841fc.js:1 Error: No language registration for bash
Please report this to https://github.com/markedjs/marked.
    at m (index-df0841fc.js:178:4456)
    at h (index-df0841fc.js:178:4651)
    at Object.k [as codeToHtml] (index-df0841fc.js:178:4838)
    at Object.renderer (index-df0841fc.js:178:6183)
    at n.renderers.<computed> (index-df0841fc.js:171:2921)
    at Fn.parse (index-df0841fc.js:170:1182)
    at parse (index-df0841fc.js:170:893)
    at wC.parse (index-df0841fc.js:171:5448)
    at ct (index-df0841fc.js:172:246)
    at au.fn (index-df0841fc.js:178:6357)
```

**To Reproduce**

1. Visit https://www.stepanrutz.com/blog/postgresql-trigram
2. The content will disappear
3. Open the the browser dev tools
4. See the error above
5. (Optional) Reload the side and see that the error will be logged the moment the content disappears.

**Expected behavior**
The content of the blog post should stay readable.

**Comment by UziTech** [comment]
Can you provide the code used to setup marked?

**Comment by adarsh-jha-dev** [comment]
Hey @Patrick-Pr can you please assign this issue to me?

**Comment by UziTech** [comment]
@adarsh-jha-dev you can work on it without it being assigned to you
