### ISSUE TITLE
Docusaurus + redocusaurus == The language "shell" has no grammar

### ISSUE THREAD

**Issue by chendrix** [markedjs/marked#3226]
**Marked version:** 4.0.15

**Describe the bug**

I am using docusaurus to generate a docs website. Within that I am also using [redocusaurus](https://redocusaurus.vercel.app/docs) to generate a website for an OpenAPI spec, which in turn uses the [redoc](https://redocly.github.io/redoc/) package which in turn uses marked.

For the rest of my docusaurus website I want to configure `bash` syntax highlighting on code blocks, so I have configured an `additionalLanguage` of `bash`. On the docusaurus side this utilizes [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer) and [prismjs](https://prismjs.com/) for its syntax highlighting.

Now when I do a `docusaurus build` it fails with this strange stack trace. The stack trace mentions reporting a bug with **you**, which to me is odd.

```bash
✖ Server
  Compiled with some errors in 1.27m

Error: Docusaurus server-side rendering could not render static page with path /api because of error: The language "shell" has no grammar.
Please report this to https://github.com/markedjs/marked.
    at serverEntry_render (main:236019:358)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
    at async /Users/chendrix/code/docs/docs-website/node_modules/p-map/index.js:57:22 {
  [cause]: Error: The language "shell" has no grammar.
  Please report this to https://github.com/markedjs/marked.
      at Object.highlight (main:312182:11)
      at jt (main:317105:11348)
      at Object.highlight (main:317105:51595)
      at $r.code (main:317105:41351)
      at Cr.parse (main:317105:44500)
      at Cr.parse (main:317105:45485)
      at Cr.parse (main:317105:43784)
      at Ar (main:317105:47911)
      at Ur.renderMd (main:317105:53412)
      at Rs.render (main:317958:680)
}

Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/chendrix/code/docs/docs-website/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async mapAsyncSequential (/Users/chendrix/code/docs/docs-website/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/Users/chendrix/code/docs/docs-website/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: Error: Failed to compile due to Webpack errors.
  Error: Docusaurus server-side rendering could not render static page with path /api because of error: The language "shell" has no grammar.
  Please report this to https://github.com/markedjs/marked.
      at /Users/chendrix/code/docs/docs-website/node_modules/@docusaurus/core/lib/webpack/utils.js:207:24
      at /Users/chendrix/code/docs/docs-website/node_modules/webpack/lib/MultiCompiler.js:554:14
      at processQueueWorker (/Users/chendrix/code/docs/docs-website/node_modules/webpack/lib/MultiCompiler.js:491:6)
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
}

[INFO] Docusaurus version: 3.1.1
Node version: v21.6.2
make: *** [build] Error 1
```

**To Reproduce**

Unsure. Our docs website code is currently internal.

**Expected behavior**

My `build` process not to fail.

**Comment by chendrix** [comment]
Oh also of note, we're not importing / using `marked-highlight` at all...

**Comment by UziTech** [comment]
This looks like a prismjs issue that it doesn't support shell grammar.

**Comment by chendrix** [comment]
@UziTech prismjs **does** support shell grammar –– it has a `bash` language that works with 

```
 ```shell
 ```sh
 ```bash
```

**Comment by UziTech** [comment]
This sounds like a question that should be asked to prismjs
