### ISSUE TITLE
could not resolve module

### ISSUE THREAD

**Issue by fendypurnomo** [markedjs/marked#3279]
ERROR: D:/applications/docs/angular.io/adev/src/content/guide/components/BUILD.bazel:3:16: Action adev/src/content/guide/components/advanced-configuration.md.html failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat ... (remaining 2 arguments skipped)      
Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48611:19)
    at Runfiles.resolveWorkspaceRelative (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48620:21)   
    at getMermaidScriptTagData (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48699:36)
    at Object.processMermaidCodeBlock (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48712:29)      
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
    at async Promise.all (index 265)
    at main (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52239:31)

**Comment by UziTech** [comment]
Looks like one of your marked extensions is missing a file `angular/node_modules/mermaid/dist/mermaid.js`

**Comment by fendypurnomo** [comment]
The mermaid.js file is in node_modules/mermaid/dist/mermaid.js, but I repeatedly try to run the command "yarn run docs", the result is the error

**Comment by UziTech** [comment]
What extensions do you have installed for marked?

**Comment by fendypurnomo** [comment]
I have installed marked like this
![image](https://github.com/markedjs/marked/assets/20944934/373775da-60d3-4761-a82b-1e6dc83aa40f)

**Comment by fendypurnomo** [comment]
This node_modules/mermaid
![image](https://github.com/markedjs/marked/assets/20944934/90f2807e-3781-4f78-9a77-89ebc2f1f8c8)

**Comment by UziTech** [comment]
Can you create a minimal repo? Without actually seeing the code I can't help debug this issue.

**Comment by fendypurnomo** [comment]
I'm cloning angular/angular.git repo, and then i'm running commond `yarn docs` or `yarn bazel run adev:serve`, then i got an error like below:

Administrator@DESKTOP-19BVUE8 MINGW64 /d/Applications/docs/angular.io (main)
$ yarn bazel run adev:serve
yarn run v1.22.19
$ D:\Applications\docs\angular.io\node_modules\.bin\bazel run adev:serve

INFO: Build option --//adev:fast_build_mode has changed, discarding analysis cache.
INFO: Analyzed target //adev:serve (1 packages loaded, 82781 targets configured).
INFO: Found 1 target...

ERROR: D:/applications/docs/angular.io/adev/src/content/guide/components/BUILD.bazel:3:16: Action adev/src/content/guide/components/advanced-configuration.md.html failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat ... (remaining 2 arguments skipped)

Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48611:19)
    at Runfiles.resolveWorkspaceRelative (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48620:21)
    at getMermaidScriptTagData (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48699:36)
    at Object.processMermaidCodeBlock (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48712:29)
    at async Promise.all (index 264)
    at main (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52240:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.

ERROR: D:/applications/docs/angular.io/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat ... (remaining 2 arguments skipped)

INFO: Elapsed time: 238.018s, Critical Path: 135.58s
INFO: 92 processes: 5 internal, 87 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by UziTech** [comment]
I see you opened an issue in the angular repo https://github.com/angular/angular/issues/55657. I'm going to close this as this is an angular issue not maked

**Comment by fendypurnomo** [comment]
Ok, thanks @UziTech
