### ISSUE TITLE
marked 13: TypeError: Cannot read properties of undefined (reading 'header') at _Renderer.tablecell

### ISSUE THREAD

**Issue by benmccann** [markedjs/marked#3323]
**Marked version:** 13.0.0

**Describe the bug**
```
TypeError: Cannot read properties of undefined (reading 'header')
Please report this to https://github.com/markedjs/marked.
    at _Renderer.tablecell (sites/kit.svelte.dev/.svelte-kit/output/server/chunks/index3.js:3915:24)
    at renderer.<computed> [as tablecell] (node_modules/.pnpm/marked@13.0.0/node_modules/marked/lib/marked.esm.js:2259:48)
    at _Renderer.<anonymous> (node_modules/.pnpm/marked@13.0.0/node_modules/marked/lib/marked.esm.js:2381:38)
    at renderer.<computed> [as table] (node_modules/.pnpm/marked@13.0.0/node_modules/marked/lib/marked.esm.js:2259:48)
    at _Parser.parse (node_modules/.pnpm/marked@13.0.0/node_modules/marked/lib/marked.esm.js:1962:42)
    at parse (node_modules/.pnpm/marked@13.0.0/node_modules/marked/lib/marked.esm.js:1918:23)
    at Marked.parse (node_modules/.pnpm/marked@13.0.0/node_modules/marked/lib/marked.esm.js:2611:28)
    at transform (sites/kit.svelte.dev/.svelte-kit/output/server/chunks/index3.js:3977:23)
    at parse (sites/kit.svelte.dev/.svelte-kit/output/server/chunks/index3.js:4065:25)
    at render_content_markdown (sites/kit.svelte.dev/.svelte-kit/output/server/chunks/index3.js:4003:10)

node:internal/event_target:1099
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /docs/migrating (linked from /docs/introduction)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at packages/kit/src/core/config/options.js:202:13
    at packages/kit/src/core/postbuild/prerender.js:65:25
    at save (packages/kit/src/core/postbuild/prerender.js:413:4)
    at visit (packages/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
```

**To Reproduce**
```
git clone git@github.com:sveltejs/kit.git
cd kit/sites/kit.svelte.dev
```
Edit `package.json` to use `marked` 13
```
pnpm install
pnpm build
```

**Expected behavior**
The site should build successfully

**Comment by UziTech** [comment]
What extensions are you using?

**Comment by benmccann** [comment]
Ah, thank you. I've filed https://github.com/sveltejs/site-kit/issues/296 in place of this issue
