### ISSUE TITLE
Custom renderer not working

### ISSUE THREAD

**Issue by qianmoQ** [markedjs/marked#3574]
**Marked version:**

**Describe the bug**

```
const {marked} = require("marked");
const {loadComponent} = require('../../component-loader');
const PageForgeImageExtension = require('./pageforge-image');
const PageForgeLinkExtension = require('./pageforge-link');
const PageForgeCodeBlockExtension = require('./pageforge-code-block');
const PageForgeQuoteInlineCodeExtension = require('./pageforge-quote-inline-code');
const PageForgeHeadingExtension = require('./pageforge-heading');
const PageForgeAlertExtension = require('./pageforge-alert');
const PageForgeTabExtension = require('./pageforge-tabs');
const PageForgeTableExtension = require('./pageforge-table');

const renderer = {
    paragraph({tokens}) {
        return `<p>${this.parser.parseInline(tokens)}</p>\n`;
    },
    space(item) {
        return loadComponent('space');
    },
    hr(item) {
        return loadComponent('hr');
    },
    text(item) {
        if (item?.tokens) {
            item.text = this.parser.parseInline(item.tokens)
        }

        return loadComponent('span', {
            text: item.text
        });
    },
    link(item) {
        return loadComponent('a', {
            linkItem: {
                ...item,
                raw: item.raw  // 保留原始 markdown 文本
            }
        });
    },
    listitem(item) {
        console.log('list-item parse');
        item.text = this.parser.parseInline(item.tokens)
        return loadComponent('list-item', item);
    },
    list(item) {
        if (item?.items) {
            item.text = item.items
                .map(listItem => this.parser.parse(listItem.tokens))
                .join('\n');
        }
        return loadComponent('list', item);
    },
    image(item) {
        return loadComponent('image', {
            item
        });
    },
    codespan(item) {
        return loadComponent('span-code', {
            text: item.text
        });
    }
};

marked.use({
    extensions: [
        PageForgeImageExtension,
        PageForgeLinkExtension,
        PageForgeCodeBlockExtension,
        PageForgeQuoteInlineCodeExtension,
        PageForgeHeadingExtension,
        PageForgeAlertExtension,
        PageForgeTabExtension,
        PageForgeTableExtension
    ],
    renderer,
    breaks: false
});

module.exports = marked;
```

**To Reproduce**

MyData

```
- `title`: 网站标题
- `hiddenTitle`: 是否隐藏标题，默认为 `false`，设置后 logo 右侧的标题将会隐藏
- `description`: 网站描述
- `logo`: 网站图标
- `favicon`: 网站图标
- [ ]: xx
- [x]: xx
```

**Expected behavior**

`listitem(item)` not working

**Comment by qianmoQ** [comment]
@UziTech Thank you very much, please help me

**Comment by UziTech** [comment]
The listitem renderer is called from the list renderer in marked

https://github.com/markedjs/marked/blob/33eb5c6a3a9822035c9faf69b19af73d8a747714/src/Renderer.ts#L67

It looks like your new list renderer doesn't call it.

**Comment by qianmoQ** [comment]
> The listitem renderer is called from the list renderer in marked
> 
> https://github.com/markedjs/marked/blob/33eb5c6a3a9822035c9faf69b19af73d8a747714/src/Renderer.ts#L67
> 
> It looks like your new list renderer doesn't call it.

```
    listitem(item) {
        item.text = this.parser.parseInline(item.tokens)
        return loadComponent('list-item', item);
    },
    list(item) {
        let body = '';
        for (let j = 0; j < item.items.length; j++) {
            const item = item.items[j];
            body += this.listitem(item);
        }
        item.text =body
        return loadComponent('list', item);
    },
```

Has error

```
Error: 🤯 启动服务失败 Cannot access 'item' before initialization
Please report this to https://github.com/markedjs/marked.
    at ServeCommand.execute (/Users/shicheng/Code/pageforge/lib/commands/serve.js:23:19)
    at async main (/Users/shicheng/Code/pageforge/bin/pageforge.js:64:13)
```

**Comment by qianmoQ** [comment]
OK, thank you very much, I understand. I just need to implement my analysis according to this implementation method.
